const products = [
    { id: 1, name: "Phone A", category: "Electronics", tags: ["mobile", "smartphone"], image: "img/phoneA.jpg", price: 300 },
    { id: 2, name: "Laptop B", category: "Electronics", tags: ["laptop", "computer"], image: "img/laptopB.jpg", price: 1200 },
    { id: 3, name: "Shoes C", category: "Fashion", tags: ["footwear", "shoes"], image: "img/shoesC.jpg", price: 50 },
    { id: 4, name: "Tablet D", category: "Electronics", tags: ["tablet", "mobile"], image: "img/tabletD.jpg", price: 200 },
    { id: 5, name: "Shirt E", category: "Fashion", tags: ["clothing", "shirt"], image: "img/shirtE.jpg", price: 25 },
    { id: 6, name: "Smartwatch F", category: "Electronics", tags: ["wearable", "watch"], image: "img/smartwatchF.jpg", price: 150 },
    { id: 7, name: "Camera G", category: "Electronics", tags: ["camera", "photography"], image: "img/cameraG.jpg", price: 500 },
    { id: 8, name: "Headphones H", category: "Electronics", tags: ["headphones", "audio"], image: "img/headphonesH.jpg", price: 80 },
    { id: 9, name: "Bag I", category: "Fashion", tags: ["accessory", "bag"], image: "img/bagI.jpg", price: 35 },
    { id: 10, name: "T-shirt J", category: "Fashion", tags: ["clothing", "t-shirt"], image: "img/tshirtJ.jpg", price: 20 },
    { id: 11, name: "Jeans K", category: "Fashion", tags: ["clothing", "jeans"], image: "img/jeansK.jpg", price: 40 },
    { id: 12, name: "Jacket L", category: "Fashion", tags: ["clothing", "jacket"], image: "img/jacketL.jpg", price: 75 },
    { id: 13, name: "Dress M", category: "Fashion", tags: ["clothing", "dress"], image: "img/dressM.jpg", price: 60 },
    { id: 14, name: "Sneakers N", category: "Fashion", tags: ["footwear", "sneakers"], image: "img/sneakersN.jpg", price: 55 },
    { id: 15, name: "Blouse O", category: "Fashion", tags: ["clothing", "blouse"], image: "img/blouseO.jpg", price: 30 },
    { id: 16, name: "Boots P", category: "Fashion", tags: ["footwear", "boots"], image: "img/bootsP.jpg", price: 65 },
    { id: 17, name: "Scarf Q", category: "Fashion", tags: ["accessory", "scarf"], image: "img/scarfQ.jpg", price: 15 },
    { id: 18, name: "Sweater R", category: "Fashion", tags: ["clothing", "sweater"], image: "img/sweaterR.jpg", price: 45 },
    { id: 19, name: "Hat S", category: "Fashion", tags: ["accessory", "hat"], image: "img/hatS.jpg", price: 25 },
    { id: 20, name: "Gloves T", category: "Fashion", tags: ["accessory", "gloves"], image: "img/glovesT.jpg", price: 20 },
    { id: 21, name: "Smartphone Case U", category: "Electronics", tags: ["accessory", "case"], image: "img/caseU.jpg", price: 15 },
    { id: 22, name: "Wireless Charger V", category: "Electronics", tags: ["charger", "wireless"], image: "img/chargerV.jpg", price: 30 },
    { id: 23, name: "Bluetooth Speaker W", category: "Electronics", tags: ["audio", "speaker"], image: "img/speakerW.jpg", price: 60 },
    { id: 24, name: "Smart TV X", category: "Electronics", tags: ["tv", "smart"], image: "img/tvX.jpg", price: 900 },
    { id: 25, name: "Bluetooth Earbuds Y", category: "Electronics", tags: ["audio", "earbuds"], image: "img/earbudsY.jpg", price: 100 },
    { id: 26, name: "Backpack Z", category: "Fashion", tags: ["accessory", "backpack"], image: "img/backpackZ.jpg", price: 40 },
    { id: 27, name: "Sunglasses A1", category: "Fashion", tags: ["accessory", "sunglasses"], image: "img/sunglassesA1.jpg", price: 50 },
    { id: 28, name: "Pants B1", category: "Fashion", tags: ["clothing", "pants"], image: "img/pantsB1.jpg", price: 35 },
    { id: 29, name: "Watch C1", category: "Fashion", tags: ["accessory", "watch"], image: "img/watchC1.jpg", price: 80 },
    { id: 30, name: "Sweatshirt D1", category: "Fashion", tags: ["clothing", "sweatshirt"], image: "img/sweatshirtD1.jpg", price: 50 },
    { id: 31, name: "Cardigan E1", category: "Fashion", tags: ["clothing", "cardigan"], image: "img/cardiganE1.jpg", price: 55 },
    { id: 32, name: "Blazer F1", category: "Fashion", tags: ["clothing", "blazer"], image: "img/blazerF1.jpg", price: 120 },
    { id: 33, name: "Skirt G1", category: "Fashion", tags: ["clothing", "skirt"], image: "img/skirtG1.jpg", price: 40 },
    { id: 34, name: "Leggings H1", category: "Fashion", tags: ["clothing", "leggings"], image: "img/leggingsH1.jpg", price: 30 },
    { id: 35, name: "Tote Bag I1", category: "Fashion", tags: ["accessory", "tote bag"], image: "img/totebagI1.jpg", price: 45 },
    { id: 36, name: "Summer Dress J1", category: "Fashion", tags: ["clothing", "dress"], image: "img/summerdressJ1.jpg", price: 75 },
    { id: 37, name: "Denim Jacket K1", category: "Fashion", tags: ["clothing", "denim jacket"], image: "img/denimjacketK1.jpg", price: 90 },
    { id: 38, name: "Flannel Shirt L1", category: "Fashion", tags: ["clothing", "flannel shirt"], image: "img/flannelshirtL1.jpg", price: 55 },
    { id: 39, name: "Puffer Coat M1", category: "Fashion", tags: ["clothing", "puffer coat"], image: "img/puffercoatM1.jpg", price: 130 },
    { id: 40, name: "Bootcut Jeans N1", category: "Fashion", tags: ["clothing", "jeans"], image: "img/bootcutjeansN1.jpg", price: 65 },
    { id: 41, name: "Poncho O1", category: "Fashion", tags: ["clothing", "poncho"], image: "img/ponchoO1.jpg", price: 40 },
    { id: 42, name: "Blouse P1", category: "Fashion", tags: ["clothing", "blouse"], image: "img/blouseP1.jpg", price: 45 },
    { id: 43, name: "Track Pants Q1", category: "Fashion", tags: ["clothing", "track pants"], image: "img/trackpantsQ1.jpg", price: 35 },
    { id: 44, name: "Kimono R1", category: "Fashion", tags: ["clothing", "kimono"], image: "img/kimonoR1.jpg", price: 80 },
    { id: 45, name: "Cargo Shorts S1", category: "Fashion", tags: ["clothing", "shorts"], image: "img/cargoshortsS1.jpg", price: 30 }
];
